#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PI 3.14159265358979323846

#define VENTANA_ANCHO 1366
#define VENTANA_ALTO 768

#define JUEGO_FPS 100
#define JUEGO_COMBUSTIBLE_INICIAL 9999
#define JUEGO_COMBUSTIBLE_RADIANES 1
#define JUEGO_COMBUSTIBLE_POT_X_SEG 1

#define GRAVEDAD 5

#define NAVE_ROTACION_PASO (PI/20)
#define NAVE_MAX_POTENCIA (3*GRAVEDAD)
#define NAVE_POTENCIA_PASO (NAVE_MAX_POTENCIA / 10)

#define NAVE_X_INICIAL 100
#define NAVE_Y_INICIAL (VENTANA_ALTO - 100)
#define NAVE_VX_INICIAL 100
#define NAVE_VY_INICIAL 0
#define NAVE_ANGULO_INICIAL (PI/2)
#define NAVE_POTENCIA_INICIAL 0

#define ANGULO_LANDED 0.01
#define VX_DESTROYED 2
#define VY_DESTROYED 20
#define VX_LANDED 1
#define VY_LANDED 10

#define PUNTAJE_DESTROYED 5
#define PUNTAJE_LANDED_HARD 15
#define PUNTAJE_LANDED 50

#define COMBUSTIBLE_PENALIDAD 250

#define CARACTERES_ESCALAMIENTO 2

#endif // _CONFIG_H_
